name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag integrationtest:$GITHUB_SHA
    
    - name: Run python tests
      run: docker run --rm integrationtest:$GITHUB_SHA python manage.py test 
